name: Build LaTeX Document
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: Sakul6499/GitHub-Action-LaTeX@v1.0.0
        with:
          latex_main_file: main.tex

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: main.pdf
          path: ./ 
        if: always()